In [7]:
%pip install global-land-mask

Collecting global-land-mask
  Using cached global_land_mask-1.0.0-py3-none-any.whl.metadata (5.2 kB)
Using cached global_land_mask-1.0.0-py3-none-any.whl (1.8 MB)
Installing collected packages: global-land-mask
Successfully installed global-land-mask-1.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import numpy as np
import requests
from global_land_mask import globe
pd.set_option('display.max_columns', None)
pd.set_option('display.max_columns', None)
mission_bay = pd.read_csv('C:/Users/maxph/OneDrive/Desktop/SpeciesImputation/MissionBayData.csv')
mission_bay = mission_bay.drop(['url', 'image_url', 'sound_url', 'tag_list', 'description', 'captive_cultivated', 'oauth_application_id', 'private_place_guess', 'private_latitude', 'private_longitude', 'public_positional_accuracy', 'geoprivacy', 'taxon_geoprivacy', 'coordinates_obscured', 'positioning_method', 'positioning_device', 'species_guess', 'created_at', 'updated_at'], axis = 1)
mission_bay

,id,uuid,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,user_name,quality_grade,license,num_identification_agreements,num_identification_disagreements,place_guess,latitude,longitude,positional_accuracy,scientific_name,common_name,iconic_taxon_name,taxon_id
0,168000,c38b2f25-0486-4176-9507-b11042b96c10,2012-12-02 10:22:09,2012-12-02,2012-12-02 18:22:09 UTC,Pacific Time (US & Canada),10285,finatic,BJ Stacey,research,CC-BY-NC,3,0,Mission Bay--Kendall-Frost Marsh,32.793408,-117.228756,NaN,Megaceryle alcyon,Belted Kingfisher,Aves,2548
1,168001,ba0edaba-2c45-4378-a5a7-df8d88b7b1fb,2012-12-02 10:21:45,2012-12-02,2012-12-02 18:21:45 UTC,Pacific Time (US & Canada),10285,finatic,BJ Stacey,research,CC-BY-NC,2,0,Mission Bay--Kendall-Frost Marsh,32.793408,-117.228756,NaN,Sayornis nigricans,Black Phoebe,Aves,17013
2,168002,d8e60d02-a1fa-4dbf-bf09-3fcac7af1a93,2012-12-02 10:21:02,2012-12-02,2012-12-02 18:21:02 UTC,Pacific Time (US & Canada),10285,finatic,BJ Stacey,research,CC-BY-NC,2,0,Mission Bay--Kendall-Frost Marsh,32.793408,-117.228756,NaN,Ardea herodias,Great Blue Heron,Aves,4956
3,168003,8c95664d-93ef-4d5d-9693-2f40e155c1f7,2012-12-02 10:13:45,2012-12-02,2012-12-02 18:13:45 UTC,Pacific Time (US & Canada),10285,finatic,BJ Stacey,research,CC-BY-NC,2,0,Mission Bay--Kendall-Frost Marsh,32.793408,-117.228756,NaN,Mareca americana,American Wigeon,Aves,485176
4,168004,8de06619-47e7-4f07-9f7b-8b7fdebee5ef,2012-12-02 10:07:26,2012-12-02,2012-12-02 18:07:26 UTC,Pacific Time (US & Canada),10285,finatic,BJ Stacey,research,CC-BY-NC,2,0,Mission Bay--Kendall-Frost Marsh,32.793408,-117.228756,NaN,Egretta thula,Snowy Egret,Aves,4940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4151,336549231,3c4d91f2-cfaf-4658-ab0f-4b82025ccb02,2026-01-23 16:10:01,2026-01-23,2026-01-24 00:10:01 UTC,Pacific Time (US & Canada),4536577,clarissarodd,Clarissa Rodriguez,research,CC-BY-NC,3,0,"Pacific Beach Dr, San Diego, CA, US",32.795690,-117.230467,17.0,Astur cooperii,Cooper's Hawk,Aves,1579017
4152,336656287,7da09285-1487-4153-8621-ed52a421c6c8,2026/01/29 12:18 PM,2026-01-29,2026-01-29 20:18:00 UTC,Pacific Time (US & Canada),9836153,cade_,NaN,research,CC-BY-NC,1,0,"Mission Bay, San Diego, CA, USA",32.793286,-117.223939,5.0,Charadrius semipalmatus,Semipalmated Plover,Aves,4817
4153,336656288,1031c9cd-ab7c-4255-aca8-a7d69821758e,2026/01/29 12:30 PM,2026-01-29,2026-01-29 20:30:00 UTC,Pacific Time (US & Canada),9836153,cade_,NaN,research,CC-BY-NC,1,0,"Mission Bay, San Diego, CA, USA",32.793278,-117.223944,5.0,Limosa fedoa,Marbled Godwit,Aves,3954
4154,336656289,abf0b45d-bc56-4d16-9be9-36f131626e25,2026/01/29 12:42 PM,2026-01-29,2026-01-29 20:42:00 UTC,Pacific Time (US & Canada),9836153,cade_,NaN,research,CC-BY-NC,1,0,"Mission Bay, San Diego, CA, USA",32.793281,-117.223944,5.0,Calidris mauri,Western Sandpiper,Aves,3855
4155,336656315,0fbd0304-a67a-4767-92a8-66dba79f3390,2026/01/29 12:56 PM,2026-01-29,2026-01-29 20:56:00 UTC,Pacific Time (US & Canada),9836153,cade_,NaN,research,CC-BY-NC,1,0,"Mission Bay, San Diego, CA, USA",32.793164,-117.223928,NaN,Actitis macularius,Spotted Sandpiper,Aves,72458

In [21]:
mission_bay['time_observed_at'] = pd.to_datetime(mission_bay['time_observed_at'])
mission_bay = mission_bay.sort_values(by= ['scientific_name', 'time_observed_at'])
mission_bay

,id,uuid,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,user_name,quality_grade,license,num_identification_agreements,num_identification_disagreements,place_guess,latitude,longitude,positional_accuracy,scientific_name,common_name,iconic_taxon_name,taxon_id
1966,176306407,8d63929f-9ec1-4d9e-93b0-de328f7a9941,2023/07/30 10:21 PM,2023-07-30,2023-07-31 05:21:00+00:00,Pacific Time (US & Canada),1503814,bbesom,NaN,needs_id,CC-BY-NC,0,0,"Mission Bay, San Diego, CA, USA",32.795903,-117.229256,61.0,Abegesta remellalis,White-trimmed Abegesta,Insecta,363292
3470,298998948,0f548220-369f-48f6-8b3b-c74b9786d5f9,2025-07-17 21:16:24,2025-07-17,2025-07-18 04:16:24+00:00,Pacific Time (US & Canada),1422818,kuyeda,Kellie Uyeda,research,CC-BY-NC,1,0,"Pacific Beach, San Diego, CA, USA",32.795745,-117.230526,5.0,Abegesta remellalis,White-trimmed Abegesta,Insecta,363292
1098,78799546,975145e7-2eda-41fd-8f0a-643aff63802e,Wed May 05 2021 14:10:29 GMT-0700 (PDT),2021-05-05,2021-05-05 21:10:29+00:00,Pacific Time (US & Canada),4162991,jose_a,NaN,needs_id,CC-BY-NC,2,0,"Mission Bay Park, San Diego, CA, US",32.790855,-117.229788,6.0,Abronia,sand verbenas,Plantae,50255
42,6512123,89ceba65-efd0-4a00-8627-c71ddeb26edd,Sun Jun 04 2017 15:59:09 GMT-0700 (PDT),2017-06-04,2017-06-04 22:59:09+00:00,Pacific Time (US & Canada),16065,isabellekay1,Isabelle Kay,research,NaN,5,0,"Mission Bay, San Diego County, US-CA, US",32.790298,-117.230352,5.0,Abronia maritima,red sand-verbena,Plantae,75244
146,10919282,dc798364-0ac6-4854-a56a-3dc55d3b5015,2018-04-11 2:31:58 PM PDT,2018-04-11,2018-04-11 21:31:58+00:00,Pacific Time (US & Canada),850379,karlm,NaN,research,CC-BY-NC,3,0,"Mission Bay, San Diego, CA, USA",32.790279,-117.230003,NaN,Abronia maritima,red sand-verbena,Plantae,75244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022,196474961,5879fe04-65ae-4987-ab95-c785387df54b,2024-01-12 09:24:29-08:00,2024-01-12,2024-01-12 17:24:29+00:00,Pacific Time (US & Canada),1266977,icecoldwater,KGAM,research,NaN,1,0,"Northern Wildlife Preserve, San Diego, CA, US",32.795848,-117.228553,NaN,Zonotrichia leucophrys,White-crowned Sparrow,Aves,9176
2021,196474594,b221a808-82f3-41fc-bc3a-530fcfc87cfa,2024-01-12 09:32:27-08:00,2024-01-12,2024-01-12 17:32:27+00:00,Pacific Time (US & Canada),1266977,icecoldwater,KGAM,research,NaN,2,0,"Northern Wildlife Preserve, San Diego, CA, US",32.795848,-117.228553,NaN,Zonotrichia leucophrys,White-crowned Sparrow,Aves,9176
437,21120706,0e0abc60-47bd-4e77-b042-bc61db751e9a,Wed Mar 06 2019 12:42:52 GMT-0800 (PST),2019-03-06,2019-03-06 20:42:52+00:00,Pacific Time (US & Canada),1421587,claudiamedrano,claudia,needs_id,CC-BY-NC,0,0,"Mission Bay Park, San Diego, CA, US",32.789366,-117.231533,5.0,Zostera marina,Eelgrass,Plantae,52614
1335,113187217,ccb158bc-781d-4762-b8d2-f7328ccfbfbf,2022-04-27 13:31:00-07:00,2022-04-27,2022-04-27 20:31:00+00:00,Pacific Time (US & Canada),5466102,colbysees,NaN,research,CC-BY-NC,1,0,"Mission Bay Park, San Diego, CA, US",32.790438,-117.230172,10.0,Zostera marina,Eelgrass,Plantae,52614
495,34933518,436034a0-8cd3-467d-9e6b-ae47d7dcb409,Sat Oct 26 2019 15:07:06 GMT-0700 (PDT),2019-10-26,2019-10-26 22:07:06+00:00,Pacific Time (US & Canada),16065,isabellekay1,Isabelle Kay,needs_id,NaN,2,0,"Pacific Passage, San Diego, CA, US",32.789338,-117.231345,4.0,Zosteraceae,Seagrasses,Plantae,52615

In [ ]:
def filter_observations(group):
    kept_rows = []
    last_kept_time = None
    
    for _, row in group.iterrows():
        # If it's the first time seeing this species OR it's been > 5 mins
        if last_kept_time is None or (row['time_observed_at'] - last_kept_time) >= pd.Timedelta(minutes=5):
            kept_rows.append(row)
            last_kept_time = row['time_observed_at']
            
    return pd.DataFrame(kept_rows)

mission_bay_clean = mission_bay.groupby('scientific_name', group_keys = False).apply(filter_observations)
mission_bay_clean

C:\Users\maxph\AppData\Local\Temp\ipykernel_27816\3325770814.py:13: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  mission_bay_clean = mission_bay.groupby('scientific_name', group_keys = False).apply(filter_observations)

,id,uuid,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,user_name,quality_grade,license,num_identification_agreements,num_identification_disagreements,place_guess,latitude,longitude,positional_accuracy,scientific_name,common_name,iconic_taxon_name,taxon_id
1966,176306407,8d63929f-9ec1-4d9e-93b0-de328f7a9941,2023/07/30 10:21 PM,2023-07-30,2023-07-31 05:21:00+00:00,Pacific Time (US & Canada),1503814,bbesom,NaN,needs_id,CC-BY-NC,0,0,"Mission Bay, San Diego, CA, USA",32.795903,-117.229256,61.0,Abegesta remellalis,White-trimmed Abegesta,Insecta,363292
3470,298998948,0f548220-369f-48f6-8b3b-c74b9786d5f9,2025-07-17 21:16:24,2025-07-17,2025-07-18 04:16:24+00:00,Pacific Time (US & Canada),1422818,kuyeda,Kellie Uyeda,research,CC-BY-NC,1,0,"Pacific Beach, San Diego, CA, USA",32.795745,-117.230526,5.0,Abegesta remellalis,White-trimmed Abegesta,Insecta,363292
1098,78799546,975145e7-2eda-41fd-8f0a-643aff63802e,Wed May 05 2021 14:10:29 GMT-0700 (PDT),2021-05-05,2021-05-05 21:10:29+00:00,Pacific Time (US & Canada),4162991,jose_a,NaN,needs_id,CC-BY-NC,2,0,"Mission Bay Park, San Diego, CA, US",32.790855,-117.229788,6.0,Abronia,sand verbenas,Plantae,50255
42,6512123,89ceba65-efd0-4a00-8627-c71ddeb26edd,Sun Jun 04 2017 15:59:09 GMT-0700 (PDT),2017-06-04,2017-06-04 22:59:09+00:00,Pacific Time (US & Canada),16065,isabellekay1,Isabelle Kay,research,NaN,5,0,"Mission Bay, San Diego County, US-CA, US",32.790298,-117.230352,5.0,Abronia maritima,red sand-verbena,Plantae,75244
146,10919282,dc798364-0ac6-4854-a56a-3dc55d3b5015,2018-04-11 2:31:58 PM PDT,2018-04-11,2018-04-11 21:31:58+00:00,Pacific Time (US & Canada),850379,karlm,NaN,research,CC-BY-NC,3,0,"Mission Bay, San Diego, CA, USA",32.790279,-117.230003,NaN,Abronia maritima,red sand-verbena,Plantae,75244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022,196474961,5879fe04-65ae-4987-ab95-c785387df54b,2024-01-12 09:24:29-08:00,2024-01-12,2024-01-12 17:24:29+00:00,Pacific Time (US & Canada),1266977,icecoldwater,KGAM,research,NaN,1,0,"Northern Wildlife Preserve, San Diego, CA, US",32.795848,-117.228553,NaN,Zonotrichia leucophrys,White-crowned Sparrow,Aves,9176
2021,196474594,b221a808-82f3-41fc-bc3a-530fcfc87cfa,2024-01-12 09:32:27-08:00,2024-01-12,2024-01-12 17:32:27+00:00,Pacific Time (US & Canada),1266977,icecoldwater,KGAM,research,NaN,2,0,"Northern Wildlife Preserve, San Diego, CA, US",32.795848,-117.228553,NaN,Zonotrichia leucophrys,White-crowned Sparrow,Aves,9176
437,21120706,0e0abc60-47bd-4e77-b042-bc61db751e9a,Wed Mar 06 2019 12:42:52 GMT-0800 (PST),2019-03-06,2019-03-06 20:42:52+00:00,Pacific Time (US & Canada),1421587,claudiamedrano,claudia,needs_id,CC-BY-NC,0,0,"Mission Bay Park, San Diego, CA, US",32.789366,-117.231533,5.0,Zostera marina,Eelgrass,Plantae,52614
1335,113187217,ccb158bc-781d-4762-b8d2-f7328ccfbfbf,2022-04-27 13:31:00-07:00,2022-04-27,2022-04-27 20:31:00+00:00,Pacific Time (US & Canada),5466102,colbysees,NaN,research,CC-BY-NC,1,0,"Mission Bay Park, San Diego, CA, US",32.790438,-117.230172,10.0,Zostera marina,Eelgrass,Plantae,52614
495,34933518,436034a0-8cd3-467d-9e6b-ae47d7dcb409,Sat Oct 26 2019 15:07:06 GMT-0700 (PDT),2019-10-26,2019-10-26 22:07:06+00:00,Pacific Time (US & Canada),16065,isabellekay1,Isabelle Kay,needs_id,NaN,2,0,"Pacific Passage, San Diego, CA, US",32.789338,-117.231345,4.0,Zosteraceae,Seagrasses,Plantae,52615

In [ ]:
import asyncio
import httpx

async def get_habitat_async(client, scientific_name):
    # Match Name
    match_url = f"https://api.gbif.org/v1/species/match?name={scientific_name}"
    resp = await client.get(match_url)
    usage_key = resp.json().get('usageKey')

    if not usage_key: return "Name not found"

    # Get Profile
    profile_url = f"https://api.gbif.org/v1/species/{usage_key}/speciesProfiles"
    profile_resp = await client.get(profile_url)
    results = profile_resp.json().get('results', [])

    if not results: return "No habitat data"
    
    info = results[0]
    habitats = [h for h in ['marine', 'freshwater', 'terrestrial'] if info.get(h)]
    return ", ".join(habitats).capitalize() if habitats else "Unknown"

async def main(names):
    async with httpx.AsyncClient() as client:
        tasks = [get_habitat_async(client, name) for name in names]
        return await asyncio.gather(*tasks)

In [ ]:
mission_bay_final = mission_bay_clean.assign(coordinates = np.array(zip(mission_bay_clean.get('latitude'), mission_bay_clean.get('longitude'))))
mission_bay_final['is_land'] = mission_bay_final['coordinates'].apply(lambda x: globe.is_land(x[0], x[1]))
mission_bay_final

,id,uuid,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,user_name,quality_grade,license,num_identification_agreements,num_identification_disagreements,place_guess,latitude,longitude,positional_accuracy,scientific_name,common_name,iconic_taxon_name,taxon_id,coordinates,is_land
1966,176306407,8d63929f-9ec1-4d9e-93b0-de328f7a9941,2023/07/30 10:21 PM,2023-07-30,2023-07-31 05:21:00+00:00,Pacific Time (US & Canada),1503814,bbesom,NaN,needs_id,CC-BY-NC,0,0,"Mission Bay, San Diego, CA, USA",32.795903,-117.229256,61.0,Abegesta remellalis,White-trimmed Abegesta,Insecta,363292,"(32.795903261, -117.2292563392)",True
3470,298998948,0f548220-369f-48f6-8b3b-c74b9786d5f9,2025-07-17 21:16:24,2025-07-17,2025-07-18 04:16:24+00:00,Pacific Time (US & Canada),1422818,kuyeda,Kellie Uyeda,research,CC-BY-NC,1,0,"Pacific Beach, San Diego, CA, USA",32.795745,-117.230526,5.0,Abegesta remellalis,White-trimmed Abegesta,Insecta,363292,"(32.7957446479, -117.2305255383)",True
1098,78799546,975145e7-2eda-41fd-8f0a-643aff63802e,Wed May 05 2021 14:10:29 GMT-0700 (PDT),2021-05-05,2021-05-05 21:10:29+00:00,Pacific Time (US & Canada),4162991,jose_a,NaN,needs_id,CC-BY-NC,2,0,"Mission Bay Park, San Diego, CA, US",32.790855,-117.229788,6.0,Abronia,sand verbenas,Plantae,50255,"(32.790855, -117.2297883333)",True
42,6512123,89ceba65-efd0-4a00-8627-c71ddeb26edd,Sun Jun 04 2017 15:59:09 GMT-0700 (PDT),2017-06-04,2017-06-04 22:59:09+00:00,Pacific Time (US & Canada),16065,isabellekay1,Isabelle Kay,research,NaN,5,0,"Mission Bay, San Diego County, US-CA, US",32.790298,-117.230352,5.0,Abronia maritima,red sand-verbena,Plantae,75244,"(32.7902978193, -117.2303516139)",True
146,10919282,dc798364-0ac6-4854-a56a-3dc55d3b5015,2018-04-11 2:31:58 PM PDT,2018-04-11,2018-04-11 21:31:58+00:00,Pacific Time (US & Canada),850379,karlm,NaN,research,CC-BY-NC,3,0,"Mission Bay, San Diego, CA, USA",32.790279,-117.230003,NaN,Abronia maritima,red sand-verbena,Plantae,75244,"(32.7902793884, -117.2300033569)",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022,196474961,5879fe04-65ae-4987-ab95-c785387df54b,2024-01-12 09:24:29-08:00,2024-01-12,2024-01-12 17:24:29+00:00,Pacific Time (US & Canada),1266977,icecoldwater,KGAM,research,NaN,1,0,"Northern Wildlife Preserve, San Diego, CA, US",32.795848,-117.228553,NaN,Zonotrichia leucophrys,White-crowned Sparrow,Aves,9176,"(32.7958483333, -117.2285533333)",True
2021,196474594,b221a808-82f3-41fc-bc3a-530fcfc87cfa,2024-01-12 09:32:27-08:00,2024-01-12,2024-01-12 17:32:27+00:00,Pacific Time (US & Canada),1266977,icecoldwater,KGAM,research,NaN,2,0,"Northern Wildlife Preserve, San Diego, CA, US",32.795848,-117.228553,NaN,Zonotrichia leucophrys,White-crowned Sparrow,Aves,9176,"(32.7958483333, -117.2285533333)",True
437,21120706,0e0abc60-47bd-4e77-b042-bc61db751e9a,Wed Mar 06 2019 12:42:52 GMT-0800 (PST),2019-03-06,2019-03-06 20:42:52+00:00,Pacific Time (US & Canada),1421587,claudiamedrano,claudia,needs_id,CC-BY-NC,0,0,"Mission Bay Park, San Diego, CA, US",32.789366,-117.231533,5.0,Zostera marina,Eelgrass,Plantae,52614,"(32.7893663384, -117.2315328756)",True
1335,113187217,ccb158bc-781d-4762-b8d2-f7328ccfbfbf,2022-04-27 13:31:00-07:00,2022-04-27,2022-04-27 20:31:00+00:00,Pacific Time (US & Canada),5466102,colbysees,NaN,research,CC-BY-NC,1,0,"Mission Bay Park, San Diego, CA, US",32.790438,-117.230172,10.0,Zostera marina,Eelgrass,Plantae,52614,"(32.7904383333, -117.2301716667)",True
495,34933518,436034a0-8cd3-467d-9e6b-ae47d7dcb409,Sat Oct 26 2019 15:07:06 GMT-0700 (PDT),2019-10-26,2019-10-26 22:07:06+00:00,Pacific Time (US & Canada),16065,isabellekay1,Isabelle Kay,needs_id,NaN,2,0,"Pacific Passage, San Diego, CA, US",32.789338,-117.231345,4.0,Zosteraceae,Seagrasses,Plantae,52615,"(32.7893377073, -117.2313449003)",True

In [ ]:
mission_bay_final['habitat'] = mission_bay_final['scientific_name'].apply(get_habitat)

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))